package tab

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"
)

var DefaultTitleEndpoints = []Endpoint{}

var notChatModel = []string{"whisper", "embed", "rerank", "tts", "speech", "voice", "diariz", "asr", "image"}

const titlePrompt = `You are naming a screen-recording session in which someone used a web app and narrated what they saw out loud.

Write ONE line, at most 70 characters, describing what happened in the session — ideally the problem the person ran into. No quotes, no trailing period, no preamble. If nothing notable happened, describe what they were doing.`

type TitleOptions struct {
	Enabled   bool
	Endpoints []Endpoint
	Model     string
	APIKey    string
	Timeout   time.Duration
}

type TitleResult struct {
	Title string
	Slug  string
	Note  string
}

func GenerateTitle(o TitleOptions, tr *Transcript, events []Event) TitleResult {
	fallback := func(note string) TitleResult {
		return TitleResult{Slug: DeterministicSlug(events), Note: note}
	}
	if !o.Enabled {
		return fallback("")
	}
	if tr == nil || !tr.OK || len(tr.Segments) == 0 {
		return fallback("no narration to summarise; used the click-derived name")
	}

	body := sessionDigest(tr, events)
	eps := o.Endpoints
	if len(eps) == 0 {
		eps = DefaultTitleEndpoints
	}
	if len(eps) == 0 {
		return fallback("no title endpoint configured; used the click-derived name")
	}
	timeout := o.Timeout
	if timeout <= 0 {
		timeout = 30 * time.Second
	}

	var last string
	for _, ep := range eps {
		for _, model := range candidateModels(o, ep, timeout) {
			title, err := chatOnce(ep.URL, model, o.APIKey, body, timeout)
			if err != nil {
				last = fmt.Sprintf("%s (%s): %v", ep.URL, model, err)
				continue
			}
			title = cleanTitle(title)
			if title == "" {
				last = fmt.Sprintf("%s (%s): empty completion", ep.URL, model)
				continue
			}
			slug := Slugify(title)
			if slug == "" {
				slug = DeterministicSlug(events)
			}
			return TitleResult{Title: title, Slug: slug,
				Note: fmt.Sprintf("generated by %s on %s", model, ep.URL)}
		}
	}
	return fallback("title generation failed — " + last)
}

func candidateModels(o TitleOptions, ep Endpoint, timeout time.Duration) []string {
	if o.Model != "" {
		return []string{o.Model}
	}
	var models []string
	if ep.Model != "" {
		models = append(models, ep.Model)
	}
	if m := servedModel(ep.URL, o.APIKey, timeout); m != "" && (len(models) == 0 || m != models[0]) {
		models = append(models, m)
	}
	return models
}

func sessionDigest(tr *Transcript, events []Event) string {
	var b strings.Builder
	b.WriteString("Narration:\n")
	for _, u := range ToUtterances(tr.Segments, 0, 0) {
		fmt.Fprintf(&b, "%s %s\n", FormatClock(u.T), oneLine(u.Text))
		if b.Len() > 8000 {
			break
		}
	}

	var clicked []string
	var problems []string
	for _, e := range events {
		switch {
		case e.Kind == "click" && len(clicked) < 40:
			label := ""
			if e.Elem != nil {
				label = firstNonEmpty(e.Elem.Text, e.Elem.AriaLabel, e.Elem.TestID, e.Elem.ID, e.Elem.Tag)
			}
			if label != "" {
				clicked = append(clicked, clip(label, 40))
			}
		case isError(e) && len(problems) < 20:
			problems = append(problems, clip(errorLine(e), 120))
		}
	}
	if len(clicked) > 0 {
		fmt.Fprintf(&b, "\nClicked: %s\n", strings.Join(clicked, ", "))
	}
	if len(problems) > 0 {
		fmt.Fprintf(&b, "\nErrors:\n%s\n", strings.Join(problems, "\n"))
	}
	return b.String()
}

func servedModel(baseURL, apiKey string, timeout time.Duration) string {
	req, err := http.NewRequest(http.MethodGet, strings.TrimSuffix(baseURL, "/")+"/models", nil)
	if err != nil {
		return ""
	}
	if apiKey != "" {
		req.Header.Set("Authorization", "Bearer "+apiKey)
	}
	resp, err := (&http.Client{Timeout: timeout}).Do(req)
	if err != nil {
		return ""
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return ""
	}
	var out struct {
		Data []struct {
			ID string `json:"id"`
		} `json:"data"`
	}
	if json.NewDecoder(resp.Body).Decode(&out) != nil {
		return ""
	}
	for _, m := range out.Data {
		id := strings.ToLower(m.ID)
		skip := false
		for _, bad := range notChatModel {
			if strings.Contains(id, bad) {
				skip = true
				break
			}
		}
		if !skip {
			return m.ID
		}
	}
	return ""
}

func chatOnce(baseURL, model, apiKey, body string, timeout time.Duration) (string, error) {
	payload, err := json.Marshal(map[string]any{
		"model":       model,
		"max_tokens":  60,
		"temperature": 0.2,
		"messages": []map[string]string{
			{"role": "system", "content": titlePrompt},
			{"role": "user", "content": body},
		},
	})
	if err != nil {
		return "", err
	}

	url := strings.TrimSuffix(baseURL, "/") + "/chat/completions"
	req, err := http.NewRequest(http.MethodPost, url, bytes.NewReader(payload))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	if apiKey != "" {
		req.Header.Set("Authorization", "Bearer "+apiKey)
	}

	resp, err := (&http.Client{Timeout: timeout}).Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("HTTP %d", resp.StatusCode)
	}

	var out struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return "", err
	}
	if len(out.Choices) == 0 {
		return "", fmt.Errorf("no choices")
	}
	return out.Choices[0].Message.Content, nil
}

func cleanTitle(s string) string {
	s = oneLine(s)
	if i := strings.IndexAny(s, "\r\n"); i >= 0 {
		s = s[:i]
	}
	s = strings.TrimSpace(strings.TrimLeft(s, "#*-• "))
	s = strings.Trim(s, `"'`)
	s = strings.TrimRight(s, ".")
	return clip(s, 80)
}
